name: cd

on:  
    push:    
        branches: [main]

jobs:
    Deploy:
        name: Deploy
        runs-on: ubuntu-latest

    steps:
        - name: Check out the code
          uses: actions/checkout@v4

        - name: Install goose
          run: go install github.com/pressly/goose/v3/cmd/goose@latest

        - name: Set up Go
          uses: actions/setup-go@v5
          with:
              go-version: "1.22"

        - name: Build the app
          run: ./scripts/buildprod.sh
