name: cd

on:  
    push:    
        branches: [main]

jobs:
    Deploy:
        name: Deploy
        runs-on: ubuntu-latest
        
        permissions:
            contents: "read"
            id-token: "write"

        env:
            CONN_STRING: ${{ secrets.DATABASE_URL}}

        steps:
            - name: Check out the code
              uses: actions/checkout@v4

            - name: Install goose
              run: go install github.com/pressly/goose/v3/cmd/goose@latest

            - name: Set up Go
              uses: actions/setup-go@v5
              with:
                  go-version: "1.22"

            - name: Build the app
              run: ./scripts/buildprod.sh

            - name: Run database migrations
              run: ./scripts/migrate_up.sh

            - id: "auth"
              uses: "google-github-actions/auth@v2"
              with:
                  credentials_json: "${{ secrets.GCP_CREDENTIALS }}"

            - name: "Set up Cloud SDK"
              uses: "google-github-actions/setup-gcloud@v2"
              with:
                  version: ">= 363.0.0"

            - name: "Use gcloud CLI"
              run: "gcloud info"

            - name: "Build and push Docker image"
              run: "gcloud builds submit --tag europe-southwest1-docker.pkg.dev/blog-aggregator-434208/blog-aggregator-ar-repo/blog-aggregator:latest ."

            - name: Deploy to Cloud Run
              run: gcloud run deploy blog-aggregator --image europe-southwest1-docker.pkg.dev/blog-aggregator-434208/blog-aggregator-ar-repo/blog-aggregator:latest --region europe-southwest1 --allow-unauthenticated --project blog-aggregator-434208 --max-instances=4
